FROM twhuang28/airflow:2.1.2-python3.6-base-v4 as jdk_full

ENV DEBIAN_FRONTEND=noninteractive

USER root
WORKDIR /opt

COPY openjdk-11.0.1_linux-x64_bin.tar.gz /opt/openjdk.tar.gz

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        curl libc6 libpam-modules krb5-user libnss3 procps\
    && mkdir jdk \
    && ls -al \
    && tar zxf openjdk.tar.gz -C jdk --strip-components=1 \
    && rm -rf openjdk.tar.gz \
    && apt-get -y --purge autoremove curl \
    && ln -sf /opt/jdk/bin/* /usr/local/bin/ \
    && rm -rf /var/lib/apt/lists/* \
    && java  --version \
    && javac --version \
    && jlink --version


RUN \
    mkdir -p /opt/spark && \
    mkdir -p /opt/spark/work-dir

COPY jars /opt/spark/jars
COPY bin /opt/spark/bin
COPY sbin /opt/spark/sbin

ENV SPARK_HOME /opt/spark


USER 50000
WORKDIR /opt/airflow
